/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eth.springreactor;

import reactor.core.publisher.Flux;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        List<Integer> elements = new ArrayList<>();
        Flux<Integer> just = Flux.just(1, 2, 3, 4);
        just.log().subscribe(elements::add);
        System.out.println(elements);
    }
}
